@startuml

-> LayoutInflact:setContentView()
LayoutInflact -> LayoutInflact:inflate()
LayoutInflact -> LayoutInflact:createViewFromTag()
LayoutInflact -> LayoutInflact:createViewFromTag()
LayoutInflact -> LayoutInflact:rInflateChildren()
LayoutInflact -> LayoutInflact:createViewFromTag()
LayoutInflact -> LayoutInflact:tryCreateView()
LayoutInflact -> LayoutInflact:onCreateView()
LayoutInflact -> LayoutInflact:CreateView()

@enduml