@startuml

-> LayoutInflact:setContentView()
LayoutInflact -> LayoutInflact:inflate()
LayoutInflact -> LayoutInflact:createViewFromTag()
LayoutInflact -> LayoutInflact:root_createViewFromTag()
LayoutInflact -> LayoutInflact:root_rInflateChildren()
LayoutInflact -> LayoutInflact:child_createViewFromTag()
LayoutInflact -> LayoutInflact:tryCreateView()
LayoutInflact -> LayoutInflact:onCreateView()
LayoutInflact -> LayoutInflact:CreateView()

@enduml