@startuml

ActivityThread-> ActivityThread:performLaunchActivity()

ActivityThread-> ContextImpl:createActivityContext()
ContextImpl-> ResourcesManager:getInstance().createBaseActivityResources()
ActivityThread-> ContextImpl:createAppContext()
ContextImpl -> LoadApk:getResources()
LoadApk -> ResourcesManager:getInstance().getResources()
ResourcesManager -> ResourcesManager:getOrCreateResources()
ResourcesManager-> ResourcesManager:createResourcesImpl()
ResourcesManager-> ResourcesManager:createAssetManager()
ResourcesManager-> ResourcesManager:loadApkAssets()
ResourcesManager-> AssetsManager:addAssetPath()[sdk28之后此方法废弃，官方推荐setApkAssets]
ResourcesManager-> AssetsManager:ApkAssets:loadOverlayFromPath()

@enduml