@startuml

ActivityThread-> ActivityThread:performLaunchActivity()

ActivityThread-> ContextImpl:createActivityContext()
ContextImpl-> ResourcesManager:getInstance().createBaseActivityResources()
ActivityThread-> ContextImpl:createAppContext()
ContextImpl -> LoadApk:getResources()
LoadApk -> ResourcesManager:getInstance().getResources()
ResourcesManager -> ResourcesManager:getOrCreateResources()
ResourcesManager-> ResourcesManager:createResourcesImpl()
ResourcesManager-> ResourcesManager:createAssetManager()
ResourcesManager-> ResourcesManager:loadApkAssets()
ResourcesManager-> AssetsManager:setAssetsPath()[sdk28之后资源插件化关键方法]
ResourcesManager-> AssetsManager:ApkAssets:loadOverlayFromPath()
ResourcesManager--> AssetsManager:addAssetsPath()[sdk23之后资源插件化关键方法]

@enduml